# Configura reglas del analizador Dart; no cambia el comportamiento de la aplicación en ejecución.
analyzer:
  exclude:
    - build/**
    - android/**
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    use_build_context_synchronously: false
